### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by mfirry** [heroku/scala-getting-started#4]
Can we expect a version using sbt 1.x, Scala 2.12 and Play 2.7?

**Comment by sentenza** [comment]
Bump!

While trying to deploy a Play 2.7.x app:

```
Not a supported Play version: 2.7.3. This plugin is compatible with: [PLAY_2_2_X, PLAY_2_3_X, PLAY_2_4_X, PLAY_2_5_X, PLAY_2_6_X].
```

**Comment by Malax** [comment]
This should be fixed with the recent update I made to the app which also brings it up to date for modern Scala, sbt and Play. Feel free to open another issue or re-open this one should it still be relevant. Thanks!
